/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DetectRouteImport } from './routes/detect'
import { Route as DehazeRouteImport } from './routes/dehaze'
import { Route as ClassifyRouteImport } from './routes/classify'
import { Route as AnprRouteImport } from './routes/anpr'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as IndexRouteImport } from './routes/index'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectRoute = DetectRouteImport.update({
  id: '/detect',
  path: '/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const DehazeRoute = DehazeRouteImport.update({
  id: '/dehaze',
  path: '/dehaze',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyRoute = ClassifyRouteImport.update({
  id: '/classify',
  path: '/classify',
  getParentRoute: () => rootRouteImport,
} as any)
const AnprRoute = AnprRouteImport.update({
  id: '/anpr',
  path: '/anpr',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/anpr': typeof AnprRoute
  '/classify': typeof ClassifyRoute
  '/dehaze': typeof DehazeRoute
  '/detect': typeof DetectRoute
  '/events': typeof EventsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/anpr': typeof AnprRoute
  '/classify': typeof ClassifyRoute
  '/dehaze': typeof DehazeRoute
  '/detect': typeof DetectRoute
  '/events': typeof EventsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/anpr': typeof AnprRoute
  '/classify': typeof ClassifyRoute
  '/dehaze': typeof DehazeRoute
  '/detect': typeof DetectRoute
  '/events': typeof EventsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyse'
    | '/anpr'
    | '/classify'
    | '/dehaze'
    | '/detect'
    | '/events'
    | '/sitemap.xml'
    | '/watchlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyse'
    | '/anpr'
    | '/classify'
    | '/dehaze'
    | '/detect'
    | '/events'
    | '/sitemap.xml'
    | '/watchlist'
  id:
    | '__root__'
    | '/'
    | '/analyse'
    | '/anpr'
    | '/classify'
    | '/dehaze'
    | '/detect'
    | '/events'
    | '/sitemap.xml'
    | '/watchlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyseRoute: typeof AnalyseRoute
  AnprRoute: typeof AnprRoute
  ClassifyRoute: typeof ClassifyRoute
  DehazeRoute: typeof DehazeRoute
  DetectRoute: typeof DetectRoute
  EventsRoute: typeof EventsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WatchlistRoute: typeof WatchlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detect': {
      id: '/detect'
      path: '/detect'
      fullPath: '/detect'
      preLoaderRoute: typeof DetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dehaze': {
      id: '/dehaze'
      path: '/dehaze'
      fullPath: '/dehaze'
      preLoaderRoute: typeof DehazeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify': {
      id: '/classify'
      path: '/classify'
      fullPath: '/classify'
      preLoaderRoute: typeof ClassifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anpr': {
      id: '/anpr'
      path: '/anpr'
      fullPath: '/anpr'
      preLoaderRoute: typeof AnprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyseRoute: AnalyseRoute,
  AnprRoute: AnprRoute,
  ClassifyRoute: ClassifyRoute,
  DehazeRoute: DehazeRoute,
  DetectRoute: DetectRoute,
  EventsRoute: EventsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WatchlistRoute: WatchlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
